image: Visual Studio 2019

environment:
  matrix:
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python39-x64"

build: off

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python -m pip install --upgrade pip"
  - "%CMD_IN_ENV% pip install .[all] panflute==1.12.5"

before_test:
  - choco install pandoc --version 2.9.2
  - ps: $env:Path += ";C:\Program Files\Pandoc\"

test_script:
  - '%CMD_IN_ENV% pytest --color=yes -rs -m="integration or appveyor"'
