environment:

  image: Visual Studio 2017

  matrix:
    - PYTHON: "C:\\Python36"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "32"
    - PYTHON: "C:\\Python36-x64"
      PYTHON_VERSION: "3.6.x"
      PYTHON_ARCH: "64"
    - PYTHON: "C:\\Python38-x64"
      PYTHON_VERSION: "3.8.x"
      PYTHON_ARCH: "64"

build: off

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python -m pip install --upgrade pip"
  - "%CMD_IN_ENV% pip install .[all]"

before_test:
  - choco install pandoc --version 2.9.2
  - ps: $env:Path += ";C:\Program Files\Pandoc\"

test_script:
  - "%CMD_IN_ENV% pytest --color=yes -rs -m='integration and appveyor'"
