image: Visual Studio 2019

environment:
  matrix:
    - PYTHON: "C:\\Python36"
    - PYTHON: "C:\\Python36-x64"
    - PYTHON: "C:\\Python39-x64"

build: off

install:
  - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
  - "python -m pip install --upgrade pip"
  - "%CMD_IN_ENV% pip install .[webpage,dev] panflute==2.0.5"

before_test:
  - choco install pandoc --version 2.11.3.1
  - ps: $env:Path += ";C:\Program Files\Pandoc\"

test_script:
  - '%CMD_IN_ENV% pytest -m="integration or appveyor"'
