dist: trusty
sudo: false
language: python
python:
  - "3.6"
cache:
  - pip
addons:
  apt_packages:
    - pandoc
install:
  - python setup.py install
  - python setup.py sdist bdist_wheel
script: py.test
deploy:
  provider: pypi
  user: dhimmel
  password:
    secure: GpIpGSbdgT/s6M+u32kmJ6oV5uX0PqZ9hql01UYNLqpoaSYzKS5+7S47IQVGyyeoveDYAWbXlzKiuhNBzMhcLRq6rPoSxYvn3cpE8F6AV8myO1uJrFg21C/b4KYEWRX6cLpzRfoJZRVPuul4yjqG7xn1B3deJQUxzSLBr4XLILAgCjPHNjJu/s0vI0EGgXoekYx9SfRm1xqKygDOX5zAhDDtQ+NrTPKH4t4abtICz9qw9WT9si3gbTBnSxNtBXHKQ7EhNLhivGB+j09DZ0j+GU1sMLPpGFeE579g5M7fWcJfv8fshRhgi/qzqg2/NjhN5JPNLsCM/g5JUCTkQy4FUAJtmU0Vh8dbuIWvuHhB1+5ngi9K5eCb7MNvKgcGj6ZuvIzW9eJ1/4HRY0cJYUi0nr9bF5h2sR5OTBWlebGXJFVx69WDSCjWtKqZssggG5GyMHEXsDJiPqGepB/gtlUtH3o9XEDwKz6xlALD6Ox8uXd0QyoV3rQ/9k5Z/gSGb62bhANae7g0PKc41rIziFMd86GtiuTHk/DRSgSxgMU2w3eplx6+xc/vJAxHUgNoCK+A1ip8ux1kyjlvZVG9XrO1lsaQss9dWRgM+mrTdxBHpQfz+XKmzZmOtV65rRgNfepRD7zIA7lIloYNTq3wT9wj/sjnW0lbbmecOkDSIvOHjZ0=
  on:
    python: '3.6'
    repo: greenelab/manubot
    tags: true
    distributions: sdist bdist_wheel
