dist: trusty
sudo: true
language: python
python:
  - "3.6"
cache:
  - pip
before_install:
  - wget --quiet https://github.com/jgm/pandoc/releases/download/2.5/pandoc-2.5-1-amd64.deb
  - sudo dpkg --install pandoc-2.5-1-amd64.deb
install:
  - pip install .
  - python setup.py sdist bdist_wheel
script:
  - pytest
deploy:
  provider: pypi
  user: dhimmel
  password:
    secure: "KoNxGDegmLd2wNg/LFzlYvnHbKObIkwcMjyoaHFVNFMNX48zJ0lpxdX2IeLmzARhkwS7u+kIszKcP3Qwo9XmX3AP9Sh0EiyLVa5FKvSPpJP4CIoKw+dE4j5acFuQsc0ZrulzeEx99rNNkDJzsS4C3eCIxCMwtztaUl4iTA9wp5XWG7NkzqXI1nXkL1nnjbBAkKEl0oxNE/88dJscNaRrfoYZZ//hjlIP6BDKur4a17mDEcVr6c38FciwUneR/JI99fqiDqN6LchD5YGBj/jQckCaI0xdCt2SP3fTb0ragDNZO17lQt823OfGaN/FE4Dq7YCq1WsR3EMLrqBwBfMj+0tqHn1IEb+0QjRH2E06lusPx4QFg+Wzm0I99OYSCMS+ZwPES+2QnPCNGwYcMUC2NX83jXqH6t86hwQG+Lq2r2CiJXis68Y7Soq1NuBah/46HsCPlevUDCEAN3o0zEuZwSnZlgq/FsFWD4g6m7hkpb5qObJO/q9jzBikS6GGvsUAxcBXYtar3Titw11CgRgL9ydEN5ZqYd8VUo0RfjGhBJgh1OGCTuoDsPiFUe9aNG+dwOtY5y+m6oGWds7CbkFjxekFq81pxKCXXx3g1si3BGnZtcUMCdRBv1OePKKBlItFqb5uRAwZ/pwta7G1i6aMLtURZx71vxtok0Csc8vmS0I="
  on:
    python: '3.6'
    repo: manubot/manubot
    tags: true
  distributions: sdist bdist_wheel
