name: Release
on:
  release:
    types:
      - published
jobs:
  release:
    name: Create release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install Python
      uses: actions/setup-python@v2
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install build wheel
        pip install ".[webpage,dev]"
    - name: Build package
      # https://pypa-build.readthedocs.io/en/latest/
      run: python -m build --sdist --wheel --outdir=dist
    - name: Deploy package
      if: '!github.event.repository.fork'
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
        packages_dir: dist
