name: Python Package Tests

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.6, 3.7]
        os: [ubuntu-latest, windows-latest, macOS-latest]
        pandoc-version: [2.9.2]
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Install Pandoc
      uses: r-lib/actions/setup-pandoc@v1
      with:
        # pandoc-versions from 2.7.3 to 2.9.1 won't install on Windows
        # https://github.com/jgm/pandoc/issues/6071
        pandoc-version: ${{ matrix.pandoc-version }}
    - name: Install Python
      uses: actions/setup-python@v1
    - run: echo "# Test" | pandoc -t html
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ".[all]"
    - name: Test with pytest
      env:
        GITHUB_PULL_REQUEST_SHA: ${{ github.event.pull_request.head.sha }}
      run: |
        pytest -rs --color=yes -m "not pandoc_version_sensitive"
